In [1]:
from sqlalchemy import create_engine
engine = create_engine('postgresql://aqueduct:aqueduct@pg-db1.chp4ztvsitj1.us-east-2.rds.amazonaws.com:5432/postgres')

In [4]:
import pandas as pd
df = pd.read_csv('~/wines.csv', index_col='id')
df

,color,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,ph,sulphates,alcohol,quality
id,,,,,,,,,,,,,
0,white,7.0,0.17,0.74,\N,0.045,24.0,126.0,0.99420,3.26,0.38,12.2,8.0
1,red,7.7,0.64,0.21,2.2,0.077,32.0,133.0,0.99560,3.27,0.45,9.9,5.0
2,white,6.8,0.39,0.34,7.4,0.020,38.0,133.0,0.99212,3.18,0.44,12.0,\N
3,white,6.3,0.28,0.47,\N,0.040,61.0,183.0,0.99592,3.12,0.51,9.5,6.0
4,white,7.4,0.35,0.20,13.9,0.054,63.0,229.0,0.99888,3.11,0.50,8.9,\N
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6492,white,7.6,0.32,0.58,16.75,0.050,43.0,163.0,0.99990,3.15,0.54,9.2,5.0
6493,white,5.6,0.28,0.27,3.9,0.043,52.0,158.0,0.99202,3.35,0.44,10.7,7.0
6494,white,6.4,0.37,0.20,5.6,0.117,61.0,183.0,0.99459,3.24,0.43,9.5,5.0
6495,white,6.5,0.26,0.50,8.0,0.051,46.0,197.0,0.99536,3.18,0.47,9.5,5.0
6496,red,7.2,0.62,0.06,2.7,0.077,15.0,85.0,0.99746,3.51,0.54,9.5,5.0

In [5]:
df.to_sql(con=engine, index_label='id', name='wine')

497