In [1]:
import pandas as pd
import aqueduct
from aqueduct import op, check, metric

In [2]:
# You can use `localhost` if you're running this notebook on the same machine as the server.
# If you're running your notebook on a separate machine from your
# Aqueduct server, change this to the address of your Aqueduct server.
address = "http://localhost:8080"

# If you're running youre notebook on a separate machine from your
# Aqueduct server, you will have to copy your API key here rather than
# using `get_apikey()`.
api_key = aqueduct.get_apikey()
client = aqueduct.Client(api_key, address)

In [3]:
demodb = client.integration("sflake")

In [4]:
wines = demodb.sql("select * from wine;")

In [5]:
wines.get()

,id,color,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,ph,sulphates,alcohol,quality
0,0,white,7.0,0.17,0.74,NaN,0.045,24.0,126.0,0.99420,3.26,0.38,12.2,8.0
1,1,red,7.7,0.64,0.21,2.20,0.077,32.0,133.0,0.99560,3.27,0.45,9.9,5.0
2,2,white,6.8,0.39,0.34,7.40,0.020,38.0,133.0,0.99212,3.18,0.44,12.0,NaN
3,3,white,6.3,0.28,0.47,NaN,0.040,61.0,183.0,0.99592,3.12,0.51,9.5,6.0
4,4,white,7.4,0.35,0.20,13.90,0.054,63.0,229.0,0.99888,3.11,0.50,8.9,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6492,6492,white,7.6,0.32,0.58,16.75,0.050,43.0,163.0,0.99990,3.15,0.54,9.2,5.0
6493,6493,white,5.6,0.28,0.27,3.90,0.043,52.0,158.0,0.99202,3.35,0.44,10.7,7.0
6494,6494,white,6.4,0.37,0.20,5.60,0.117,61.0,183.0,0.99459,3.24,0.43,9.5,5.0
6495,6495,white,6.5,0.26,0.50,8.00,0.051,46.0,197.0,0.99536,3.18,0.47,9.5,5.0
6496,6496,red,7.2,0.62,0.06,2.70,0.077,15.0,85.0,0.99746,3.51,0.54,9.5,5.0

In [6]:
@op
def noop(df):
    return df

In [7]:
data = noop(wines)

In [8]:
data.get()

,id,color,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,ph,sulphates,alcohol,quality
0,0,white,7.0,0.17,0.74,NaN,0.045,24.0,126.0,0.99420,3.26,0.38,12.2,8.0
1,1,red,7.7,0.64,0.21,2.20,0.077,32.0,133.0,0.99560,3.27,0.45,9.9,5.0
2,2,white,6.8,0.39,0.34,7.40,0.020,38.0,133.0,0.99212,3.18,0.44,12.0,NaN
3,3,white,6.3,0.28,0.47,NaN,0.040,61.0,183.0,0.99592,3.12,0.51,9.5,6.0
4,4,white,7.4,0.35,0.20,13.90,0.054,63.0,229.0,0.99888,3.11,0.50,8.9,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6492,6492,white,7.6,0.32,0.58,16.75,0.050,43.0,163.0,0.99990,3.15,0.54,9.2,5.0
6493,6493,white,5.6,0.28,0.27,3.90,0.043,52.0,158.0,0.99202,3.35,0.44,10.7,7.0
6494,6494,white,6.4,0.37,0.20,5.60,0.117,61.0,183.0,0.99459,3.24,0.43,9.5,5.0
6495,6495,white,6.5,0.26,0.50,8.00,0.051,46.0,197.0,0.99536,3.18,0.47,9.5,5.0
6496,6496,red,7.2,0.62,0.06,2.70,0.077,15.0,85.0,0.99746,3.51,0.54,9.5,5.0

In [9]:
client.publish_flow("testing_airflow", artifacts=[data], engine="my_airflow")

The Airflow DAG file has been downloaded to: testing_airflow_airflow.py.
                    Please copy it to your Airflow server to begin execution.
Url:  http://localhost:8080/workflow/c894c74e-e943-4485-a80a-8d9a5b177d1f